### ISSUE TITLE
Missing option for Wide (Verspreide stand)

### ISSUE THREAD

**Issue by KasvanD** [JanJaapKo/DysonPureLink#18]
I'm not sure what it's called in English in the app, but in my Dutch app I have the option for my 455 to switch between 'Verspreide stand' and normal. But there's no switch for this in the Domoticz plugin... I really miss it, because I use this setting a lot.

**Comment by JanJaapKo** [comment]
Hi @KasvanD ,

Can you switch on 'Debug' logging and send me the results? The machine will report all its states so I can derive the proper commands. Also can you toggle the 'verspreide stand' from the app with the logging on? I can see then which value is changing. If the logging is too long, please put it in a txt file (and apply filtering on domoticz logging pane).

Btw: I expect that with the latest version it should show up as 'Fan focus mode'. Please let me know if that works.

**Comment by JanJaapKo** [comment]
Closing issue due no feedback. Assuming it works, otherwise please re-open.
