### ISSUE TITLE
Locale in cloud login

### ISSUE THREAD

**Issue by JanJaapKo** [JanJaapKo/DysonPureLink#19]
Locale of cloud login is now hardcoded. See if it is possible to derive from Domoticz settings. Problem is that there are no more 'Mode's on the plugin page available.

On the other hand: entering the wrong locale doesn't seem to hurt......

**Comment by Booleano75** [comment]
A possibility is to get location information from settings 

http://domoticzserverip:8080/json.htm?type=settings

and then do a reverse lookup
 
https://www.latlong.net/

or much easier but less elegant , code the string in a user variable and access it from the plugin

**Comment by JanJaapKo** [comment]
not worth the effort....
