### ISSUE TITLE
Troubles enabling the plugin in my domoticz installation after update of the plugin.

### ISSUE THREAD

**Issue by Solution40** [JanJaapKo/DysonPureLink#27]
Hello there,

I encountered an issue after a pull from the git to the latest version. Domoticz crashes after a few seconds. 

My steps:

Installed the plugin, with my "old" credentials:
connected with my old credentials and could only retrieve the S/N's from my old devices. not the hot+ cool device.
I created a new Dyson account and moved only the hot and cool to that account to see if that would make a difference.
I removed the plugin
I did a pull to make sure i had the latest version. I received some updates
And .....
Domoticz crashes after enabling the dyson hw device:
crashlog - nothing
gbd ./domoticz shows:
Can you help? Something changed in the latest pull version? (empty HW Dyson profile trying to enable: )
2020-10-03 14:24:14.369 Error: (dyson-test) Login to Dyson account failed: '400, '
2020-10-03 14:24:14.370 (dyson-test) Not logged to Dyson Web Services.
2020-10-03 14:24:14.370 (dyson-test) No devices found in Dyson cloud account
2020-10-03 14:24:14.370 Error: (dyson-test) No usable credentials found
2020-10-03 14:24:14.370 (dyson-test) Device instance created: None
2020-10-03 14:24:14.370 Error: (dyson-test) 'onStart' failed 'AttributeError':''NoneType' object has no attribute 'device_base_topic''.

Thread 4 "PluginMgr" received signal SIGSEGV, Segmentation fault.

To make it work again:

I disable the HW plugin with sqlite3:
sudo sqlite3 domoticz.db
select * from hardware;
23|dyson-test|1|94|192.168.178.247|1883||||DysonPureLink|475|30||Normal|sinterklaas@gmail.com||0|

update hardware set [enabled] = 0 where [Name] = "dyson-test";

.quit

restart domoticz

**Comment by JanJaapKo** [comment]
Hi,

I never really tested the scenario where really no device was to be found, I updated the plugin to exit when nothing found, I hope this handles it more elegant. Please pull latest version.

I hope this solves the issue, at least I could not reproduce the above.......
