### ISSUE TITLE
Failing authentication

### ISSUE THREAD

**Issue by JanJaapKo** [JanJaapKo/DysonPureLink#36]
Since new Dyson app, authentication to cloud account fails. See: 
- https://github.com/shenxn/ha-dyson/issues/5
- https://github.com/lukasroegner/homebridge-dyson-pure-cool/pull/153

**Comment by rubendewasch** [comment]
cool. thanks Jaan-Jaap

**Comment by JanJaapKo** [comment]
This issue is resolved after PR #37
